import React, { createContext, useContext, useState, ReactNode } from 'react';

// Define language types
export type Language = "en-US" | "pt-BR";

// Define the context type
type LanguageContextType = {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

// Create the context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Set up translations
const translations: Record<Language, Record<string, string>> = {
  "en-US": {
    "app.title": "MyTradingMind",
    "nav.dashboard": "Dashboard",
    "nav.journal": "Journal",
    "nav.journalEntries": "Journal Entries",
    "nav.trades": "Trades",
    "nav.analytics": "Analytics",
    "nav.calendar": "Calendar",
    "nav.settings": "Settings",
    "nav.users": "Users",
    "nav.menu": "Menu",
    
    "common.required": "Required",
    "common.add": "Added successfully",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.view": "View",
    "common.back": "Back",
    "common.reset": "Reset",
    "common.yes": "Yes",
    "common.no": "No",
    "common.notApplicable": "Not Applicable",
    "common.submit": "Submit",
    "common.submitting": "Submitting...",
    "common.itemsPerPage": "Items per page",
    "common.confirmDelete": "Are you sure you want to delete this?",
    "common.confirmDeleteDescription": "This action cannot be undone.",
    
    "risk.status": "Risk Status",
    "risk.within": "Within limit",
    "risk.approaching": "Approaching limit",
    "risk.exceeded": "Limit exceeded",
    "risk.management": "Risk Management",
    "risk.dailyLimit": "Daily Risk Limit",
    "risk.initialCapital": "Initial Capital",
    "risk.maxLoss": "Maximum Daily Loss",
    "risk.warningThreshold": "Warning Threshold",
    
    "journal.title": "Trading Journal",
    "journal.description": "Record your daily trading activities and reflections",
    "journal.entries": "Journal Entries",
    "journal.entriesDescription": "View and manage your trading journal entries",
    "journal.viewEntry": "View Journal Entry",
    "journal.editEntry": "Edit Journal Entry",
    "journal.updateDescription": "Update your journal entry with new information",
    "journal.date": "Date",
    "journal.errorReview": "Error Review",
    "journal.errorReviewDescription": "Have you reviewed your mistakes from previous trades?",
    "journal.goalHit": "Goal Hit",
    "journal.goalHitDescription": "Did you hit your trading goals from the previous day?",
    "journal.comment": "Comments",
    "journal.actions": "Actions",
    "journal.entryFor": "Journal Entry for",
    "journal.noEntries": "No journal entries found",
    "journal.errorReviewCompleted": "Error review completed",
    "journal.dailyComment": "Daily Comment",
    "journal.dailyCommentPlaceholder": "Write your daily trading reflection here...",
    "journal.previousDayGoalHit": "Previous Day Goal Hit",
    "journal.yes": "Yes",
    "journal.no": "No",
    "journal.na": "Not Applicable",
    "journal.saved": "Journal Saved",
    "journal.updated": "Journal Updated",
    "journal.submitted": "Journal Submitted",
    "journal.dailyTitle": "Daily Trading Journal",
    "journal.previousEntries": "Previous Entries",
    "journal.newEntry": "New Journal Entry",
    "journal.selectGoalStatus": "Select goal status",
    "journal.duplicateEntry": "You have already submitted a journal entry for this date.",
    "journal.deleteConfirm": "Delete Journal Entry",
    "journal.deleteConfirmMessage": "Are you sure you want to delete this journal entry? This action cannot be undone.",
    
    "settings.language": "Language",
    "settings.riskManagement": "Risk Management",
    "settings.tradingSetups": "Trading Setups",
    "settings.mistakeTypes": "Mistake Types",
    "settings.assets": "Assets",
    "settings.newSetup": "New Setup",
    "settings.addSetup": "Add Setup",
    "settings.newMistakeType": "New Mistake Type",
    "settings.addMistakeType": "Add Mistake Type",
    "settings.newAsset": "New Asset",
    "settings.addAsset": "Add Asset",
    "settings.newAssetPlaceholder": "Enter asset symbol (e.g., BTCUSD)",
    "settings.newSetupPlaceholder": "Enter setup name (e.g., Breakout)",
    "settings.newMistakePlaceholder": "Enter mistake type (e.g., FOMO)",
    "settings.noAssets": "No assets added yet",
    
    "trade.logTitle": "Trade Log",
    "trade.logDescription": "Record and track all your trading activity",
    "trade.new": "New Trade",
    "trade.list": "Trade List",
    "trade.added": "Trade Added",
    "trade.addedDescription": "Your trade has been recorded successfully.",
    "trade.updated": "Trade Updated",
    "trade.updatedDescription": "Your trade has been updated successfully.",
    "trade.financialResult": "Financial Result",
    "trade.profitLoss": "Profit/Loss",
    "trade.mistakeDescription": "Mark trades where you made mistakes for later analysis",
    "trade.modelTrade": "Model Trade",
    "trade.modelDescription": "Mark exemplary trades for future reference",
    "trade.asset": "Asset",
    "trade.setup": "Setup",
    "trade.direction": "Direction",
    "trade.entryTime": "Entry Time",
    "trade.leverage": "Leverage",
    "trade.searchAsset": "Search assets...",
    "trade.noAssetsFound": "No assets found",
    "trade.noAssets": "No assets available",
    "trade.mistake": "Was this a mistake?",
    "trade.mistakeType": "Mistake Type",
    "trade.notes": "Notes",
    "trade.log": "Log Trade",
    "trade.update": "Update Trade",
    "trade.buy": "Buy",
    "trade.sell": "Sell",
    "trade.trend": "Trend Position",
    "trade.withTrend": "With Trend",
    "trade.againstTrend": "Against Trend",
    "trade.exitTime": "Exit Time",
    "trade.edit": "Edit Trade",
    "trade.details": "Trade Details",
    "trade.dailyGoalTracker": "Daily Goal Tracker",
    "trade.goalReached": "Daily target reached!",
    "trade.goalProgress": "You are {percentage}% away from reaching today's goal.",
    "trade.goalNotReached": "Today's goal not reached.",
    "trade.todayPnL": "Today's P&L",
    "trade.target": "Target",
    "trade.riskManager": "Risk Manager",
    
    "calculator.title": "Leverage Calculator",
    "calculator.description": "Calculate the optimal leverage based on your risk parameters",
    "calculator.stopType": "Stop Loss Type",
    "calculator.percentage": "Percentage (%)",
    "calculator.dollar": "Dollar Value ($)",
    "calculator.stopPercentage": "Stop Size (%)",
    "calculator.stopDollar": "Stop Size ($)",
    "calculator.marginAmount": "Margin Amount ($)",
    "calculator.riskPercentage": "Risk Percentage (%)",
    "calculator.entryPrice": "Entry Price ($)",
    "calculator.calculate": "Calculate",
    "calculator.results": "Calculation Results",
    "calculator.suggestedLeverage": "Suggested Leverage",
    "calculator.positionSize": "Position Size",
    
    "analytics.title": "Analytics",
    "analytics.month": "Month",
    "analytics.dateRange": "Date Range",
    "analytics.profitLoss": "Profit/Loss",
    "analytics.tradeCount": "Number of Trades",
    "analytics.winRate": "Win Rate",
    "analytics.averageTrade": "Average Trade",
    "analytics.description": "Analyze your trading performance",
    "analytics.filter": "Filter",
    "analytics.reset": "Reset Filters",
    "analytics.apply": "Apply Filters",
    "analytics.traderDetails": "Trader Analytics",
    
    "users.title": "User Management",
    "users.description": "Manage mentored traders and other mentors",
    "users.new": "New User",
    "users.list": "User List",
    "users.search": "Search by name or email",
    "users.filterByRole": "Filter by role",
    "users.allRoles": "All roles",
    "users.admin": "Admin",
    "users.mentor": "Mentor",
    "users.mentored": "Mentored",
    "users.name": "Name",
    "users.email": "Email",
    "users.role": "Role",
    "users.actions": "Actions",
    "users.updated": "User Updated",
    "users.added": "User Added",
    "users.deleted": "User Deleted",
    "users.cannotDeleteSelf": "You cannot delete your own account",
    "users.noUsersFound": "No users found",
    "users.accessDenied": "Access denied. Only mentors can view this page.",
    "users.editUser": "Edit User",
    "users.addUser": "Add User",
    "users.mentor": "Mentor",
    "users.assignMentor": "Assign Mentor",
    "users.selectMentor": "Select Mentor",
    "users.saveChanges": "Save Changes",
    "users.createUser": "Create User",
    "users.emailNote": "This email will be used for login and notifications",
    "users.selectRole": "Select a role",
    "users.analyticsFor": "Analytics for",
    "users.analyticsDescription": "View detailed trading performance metrics",
    "login.title": "Login",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit": "Sign In",
    "login.rememberMe": "Remember me",
    "login.forgotPassword": "Forgot password?",
    "login.noAccount": "Don't have an account?",
    "login.signUp": "Sign up",
    "login.switchLanguage": "Switch to Portuguese",

    "dashboard.title": "Dashboard",
    "dashboard.description": "Your trading performance at a glance",
    "dashboard.completeJournal": "Complete Daily Journal",
    "dashboard.logTrade": "Log New Trade",
    "dashboard.journalRequired": "Daily Journal Required",
    "dashboard.journalRequiredDesc": "Complete your daily journal before trading to improve discipline and focus.",
    "dashboard.goToJournal": "Go to Journal",
    "dashboard.readyToTrade": "Ready to Start Trading",
    "dashboard.readyToTradeDesc": "You've completed your daily journal. Now you can log your trades.",
    "dashboard.logFirstTrade": "Log First Trade",
    "dashboard.welcome": "Welcome to Trade Compass",
    "dashboard.welcomeDesc": "Your personal trading risk and performance management system",
    "dashboard.dashboardDesc": "This dashboard will display your trading analytics once you start logging trades. First, complete your daily journal to set intentions for the day.",
    "dashboard.step1": "Step 1",
    "dashboard.step1Desc": "Complete your daily journal and error review",
    "dashboard.step2": "Step 2",
    "dashboard.step2Desc": "Log your trades with complete details",
    "dashboard.step3": "Step 3",
    "dashboard.step3Desc": "Configure your risk management settings"
  },
  "pt-BR": {
    "app.title": "MyTradingMind",
    "nav.dashboard": "Painel",
    "nav.journal": "Diário",
    "nav.journalEntries": "Entradas do Diário",
    "nav.trades": "Operações",
    "nav.analytics": "Análises",
    "nav.calendar": "Calendário",
    "nav.settings": "Configurações",
    "nav.users": "Usuários",
    "nav.menu": "Menu",
    
    "common.required": "Obrigatório",
    "common.add": "Adicionado com sucesso",
    "common.cancel": "Cancelar",
    "common.delete": "Excluir",
    "common.save": "Salvar",
    "common.edit": "Editar",
    "common.view": "Visualizar",
    "common.back": "Voltar",
    "common.reset": "Resetar",
    "common.yes": "Sim",
    "common.no": "Não",
    "common.notApplicable": "Não Aplicável",
    "common.submit": "Enviar",
    "common.submitting": "Enviando...",
    "common.itemsPerPage": "Itens por página",
    "common.confirmDelete": "Tem certeza que deseja excluir isto?",
    "common.confirmDeleteDescription": "Esta ação não pode ser desfeita.",
    
    "risk.status": "Status de Risco",
    "risk.within": "Dentro do limite",
    "risk.approaching": "Próximo ao limite",
    "risk.exceeded": "Limite excedido",
    "risk.management": "Gestão de Risco",
    "risk.dailyLimit": "Limite Diário de Risco",
    "risk.initialCapital": "Capital Inicial",
    "risk.maxLoss": "Perda Diária Máxima",
    "risk.warningThreshold": "Limite de Alerta",
    
    "journal.title": "Diário de Trading",
    "journal.description": "Registre suas atividades diárias de trading e reflexões",
    "journal.entries": "Entradas do Diário",
    "journal.entriesDescription": "Visualize e gerencie suas entradas do diário de trading",
    "journal.viewEntry": "Visualizar Entrada do Diário",
    "journal.editEntry": "Editar Entrada do Diário",
    "journal.updateDescription": "Atualize sua entrada do diário com novas informações",
    "journal.date": "Data",
    "journal.errorReview": "Revisão de Erros",
    "journal.errorReviewDescription": "Você revisou seus erros de operações anteriores?",
    "journal.goalHit": "Meta Atingida",
    "journal.goalHitDescription": "Você atingiu suas metas de trading do dia anterior?",
    "journal.comment": "Comentários",
    "journal.actions": "Ações",
    "journal.entryFor": "Entrada do Diário para",
    "journal.noEntries": "Nenhuma entrada do diário encontrada",
    "journal.errorReviewCompleted": "Revisão de erros concluída",
    "journal.dailyComment": "Comentário Diário",
    "journal.dailyCommentPlaceholder": "Escreva sua reflexão diária de trading aqui...",
    "journal.previousDayGoalHit": "Meta do Dia Anterior Atingida",
    "journal.yes": "Sim",
    "journal.no": "Não",
    "journal.na": "Não Aplicável",
    "journal.saved": "Diário Salvo",
    "journal.updated": "Diário Atualizado",
    "journal.submitted": "Diário Enviado",
    "journal.dailyTitle": "Diário de Trading Diário",
    "journal.previousEntries": "Entradas Anteriores",
    "journal.newEntry": "Nova Entrada no Diário",
    "journal.selectGoalStatus": "Selecione o status da meta",
    "journal.duplicateEntry": "Você já enviou uma entrada do diário para esta data.",
    "journal.deleteConfirm": "Excluir Entrada do Diário",
    "journal.deleteConfirmMessage": "Tem certeza que deseja excluir esta entrada do diário? Esta ação não pode ser desfeita.",
    
    "settings.language": "Idioma",
    "settings.riskManagement": "Gestão de Risco",
    "settings.tradingSetups": "Setups de Trading",
    "settings.mistakeTypes": "Tipos de Erros",
    "settings.assets": "Ativos",
    "settings.newSetup": "Novo Setup",
    "settings.addSetup": "Adicionar Setup",
    "settings.newMistakeType": "Novo Tipo de Erro",
    "settings.addMistakeType": "Adicionar Tipo de Erro",
    "settings.newAsset": "Novo Ativo",
    "settings.addAsset": "Adicionar Ativo",
    "settings.newAssetPlaceholder": "Digite o símbolo do ativo (ex: BTCUSD)",
    "settings.newSetupPlaceholder": "Digite o nome do setup (ex: Rompimento)",
    "settings.newMistakePlaceholder": "Digite o tipo de erro (ex: FOMO)",
    "settings.noAssets": "Nenhum ativo adicionado ainda",
    
    "trade.logTitle": "Registro de Operações",
    "trade.logDescription": "Registre e acompanhe todas as suas atividades de trading",
    "trade.new": "Nova Operação",
    "trade.list": "Lista de Operações",
    "trade.added": "Operação Adicionada",
    "trade.addedDescription": "Sua operação foi registrada com sucesso.",
    "trade.updated": "Operação Atualizada",
    "trade.updatedDescription": "Sua operação foi atualizada com sucesso.",
    "trade.financialResult": "Resultado Financeiro",
    "trade.profitLoss": "Lucro/Prejuízo",
    "trade.mistakeDescription": "Marque operações onde você cometeu erros para análise posterior",
    "trade.modelTrade": "Operação Modelo",
    "trade.modelDescription": "Marque operações exemplares para referência futura",
    "trade.asset": "Ativo",
    "trade.setup": "Setup",
    "trade.direction": "Direção",
    "trade.entryTime": "Hora de Entrada",
    "trade.leverage": "Alavancagem",
    "trade.searchAsset": "Buscar ativos...",
    "trade.noAssetsFound": "Nenhum ativo encontrado",
    "trade.noAssets": "Nenhum ativo disponível",
    "trade.mistake": "Foi um erro?",
    "trade.mistakeType": "Tipo de Erro",
    "trade.notes": "Observações",
    "trade.log": "Registrar Operação",
    "trade.update": "Atualizar Operação",
    "trade.buy": "Comprar",
    "trade.sell": "Vender",
    "trade.trend": "Posição da Tendência",
    "trade.withTrend": "Com a Tendência",
    "trade.againstTrend": "Contra a Tendência",
    "trade.exitTime": "Hora de Saída",
    "trade.edit": "Editar Operação",
    "trade.details": "Detalhes da Operação",
    "trade.dailyGoalTracker": "Monitoramento de Meta Diária",
    "trade.goalReached": "Meta diária alcançada!",
    "trade.goalProgress": "Você está a {percentage}% de atingir a meta de hoje.",
    "trade.goalNotReached": "Meta de hoje não alcançada.",
    "trade.todayPnL": "P&L de Hoje",
    "trade.target": "Meta",
    "trade.riskManager": "Gerenciador de Risco",
    
    "calculator.title": "Calculadora de Alavancagem",
    "calculator.description": "Calcule a alavancagem ideal com base em seus parâmetros de risco",
    "calculator.stopType": "Tipo de Stop Loss",
    "calculator.percentage": "Porcentagem (%)",
    "calculator.dollar": "Valor em Dólar ($)",
    "calculator.stopPercentage": "Tamanho do Stop (%)",
    "calculator.stopDollar": "Tamanho do Stop ($)",
    "calculator.marginAmount": "Valor da Margem ($)",
    "calculator.riskPercentage": "Porcentagem de Risco (%)",
    "calculator.entryPrice": "Preço de Entrada ($)",
    "calculator.calculate": "Calcular",
    "calculator.results": "Resultados do Cálculo",
    "calculator.suggestedLeverage": "Alavancagem Sugerida",
    "calculator.positionSize": "Tamanho da Posição",
    
    "analytics.title": "Análises",
    "analytics.month": "Mês",
    "analytics.dateRange": "Intervalo de Datas",
    "analytics.profitLoss": "Lucro/Prejuízo",
    "analytics.tradeCount": "Número de Operações",
    "analytics.winRate": "Taxa de Acerto",
    "analytics.averageTrade": "Média por Operação",
    "analytics.description": "Analise seu desempenho de trading",
    "analytics.filter": "Filtrar",
    "analytics.reset": "Resetar Filtros",
    "analytics.apply": "Aplicar Filtros",
    "analytics.traderDetails": "Análise do Trader",
    
    "users.title": "Gerenciamento de Usuários",
    "users.description": "Gerencie traders mentorados e outros mentores",
    "users.new": "Novo Usuário",
    "users.list": "Lista de Usuários",
    "users.search": "Buscar por nome ou email",
    "users.filterByRole": "Filtrar por função",
    "users.allRoles": "Todas as funções",
    "users.admin": "Administrador",
    "users.mentor": "Mentor",
    "users.mentored": "Mentorado",
    "users.name": "Nome",
    "users.email": "Email",
    "users.role": "Função",
    "users.actions": "Ações",
    "users.updated": "Usuário Atualizado",
    "users.added": "Usuário Adicionado",
    "users.deleted": "Usuário Excluído",
    "users.cannotDeleteSelf": "Você não pode excluir sua própria conta",
    "users.noUsersFound": "Nenhum usuário encontrado",
    "users.accessDenied": "Acesso negado. Apenas mentores podem visualizar esta página.",
    "users.editUser": "Editar Usuário",
    "users.addUser": "Adicionar Usuário",
    "users.mentor": "Mentor",
    "users.assignMentor": "Atribuir Mentor",
    "users.selectMentor": "Selecionar Mentor",
    "users.saveChanges": "Salvar Alterações",
    "users.createUser": "Criar Usuário",
    "users.emailNote": "Este e-mail será usado para login e notificações",
    "users.selectRole": "Selecione uma função",
    "users.analyticsFor": "Análises para",
    "users.analyticsDescription": "Veja métricas detalhadas de desempenho de trading",
    "login.title": "Login",
    "login.email": "Email",
    "login.password": "Senha",
    "login.submit": "Entrar",
    "login.rememberMe": "Lembrar-me",
    "login.forgotPassword": "Esqueceu a senha?",
    "login.noAccount": "Não tem uma conta?",
    "login.signUp": "Cadastre-se",
    "login.switchLanguage": "Mudar para Inglês",

    "dashboard.title": "Painel",
    "dashboard.description": "Sua performance de trading em um relance",
    "dashboard.completeJournal": "Completar Diário",
    "dashboard.logTrade": "Nova Operação",
    "dashboard.journalRequired": "Diário Diário Necessário",
    "dashboard.journalRequiredDesc": "Complete seu diário diário antes de operar para melhorar a disciplina e o foco.",
    "dashboard.goToJournal": "Ir para o Diário",
    "dashboard.readyToTrade": "Pronto para Começar a Operar",
    "dashboard.readyToTradeDesc": "Você completou seu diário diário. Agora você pode registrar suas operações.",
    "dashboard.logFirstTrade": "Registrar Primeira Operação",
    "dashboard.welcome": "Bem-vindo ao Trade Compass",
    "dashboard.welcomeDesc": "Seu sistema pessoal de gerenciamento de risco e performance de trading",
    "dashboard.dashboardDesc": "Este painel exibirá suas análises de trading assim que você começar a registrar operações. Primeiro, complete seu diário diário para definir intenções para o dia.",
    "dashboard.step1": "Passo 1",
    "dashboard.step1Desc": "Complete seu diário diário e revisão de erros",
    "dashboard.step2": "Passo 2",
    "dashboard.step2Desc": "Registre suas operações com detalhes completos",
    "dashboard.step3": "Passo 3",
    "dashboard.step3Desc": "Configure suas configurações de gerenciamento de risco"
  }
};

// Provider component
export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>("en-US");

  // Function to get translations
  const t = (key: string): string => {
    return translations[currentLanguage][key] || key;
  };

  // Function to change language
  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  
  return context;
};
